### ISSUE TITLE
Has the package stopped working ?

### ISSUE THREAD

**Issue by SSV0726** [mnwato/tradingview-scraper#9]
Want to know if the package has stopped working ?

**Comment by mnwato** [comment]
I haven't tested it for a while. Do you have any problems? Or did you ask because there hasn't been a release for a long time?

**Comment by asim1342** [comment]
Search by symbol doesnt work

**Comment by mnwato** [comment]
> Search by symbol doesnt work

Semms that tradingview changed it's html structure.
Working to fix it.

**Comment by mnwato** [comment]
This issue must have been solved. But note that so many changes has been happened.
Now you can upgrade with `pip install --upgrade tradingview-scraper`.

**Comment by asim1342** [comment]
@mnwato i want to get the recent ideas. i tried: https://www.tradingview.com/symbols{symbol_payload}ideas/page-{page}/?sort=recent"
but this still gets the popular one.

**Comment by mnwato** [comment]
It's because for sort=recent frontend use API to get data:
here is api:
for main(first) page:
https://www.tradingview.com/symbols/BTCUSD/ideas/?component-data-only=1&sort=recent
for page-{page}:
https://www.tradingview.com/symbols/BTCUSD/ideas/page-2/?sort=recent&component-data-only=1&sort=recent 

I will add this feature soon.
